import './app/app.module'
import './app/login/login.module'
import './app/register/register.module'
import './app/home/home.module'
import './app/profile/profile.module'
import './app/search/search.module'
import './app/navbar/navbar.module'
